### ISSUE TITLE
Review `bbytearray` error messages

### ISSUE THREAD

**Issue by gusmonod** [bloomberg/python-comdb2#56]
As was raised in https://github.com/bloomberg/python-comdb2/pull/55#issuecomment-1864113802, perhaps we should add a test verifying the R8 error message, in particular when it comes to the `bbytearray` type.

**Comment by godlygeek** [comment]
I didn't mean to add an automated test verifying this, just to spot check it manually. The results from the current version are:
```sh
$ cdb2sql mattdb default "insert into bytearray_test(flags) values ('a')"
[insert into bytearray_test(flags) values ('a')] failed with rc 113 incompatible values from SQL string of length 1 to bytearray field 'flags' for table 'bytearray_test'
```

So, seems like the PR was correct after all. Looks like it changed in Comdb2 [here](https://github.com/bloomberg/comdb2/commit/7ccf8485c14756833e832722d8b2a7330216aa5a#diff-2b88c418965c2c4653d6f7afd1ee4b269be58cdb47dcf2b09b89207a79c97160R1385), so the PR is correct after all, just not for the reason you thought 😄
